### PR TITLE
Add core GUI functionality

### PR DESCRIPTION
**Pull request by Ty7ak**
Added basic GUI functionality. Now the app opens a GUI where you can choose a file using the system's explorer, manually change the resolution, choose a color format using a list of already supported formats. The preview also updates after pressing the "Update preview" button.

Closes #23

### CODE REVIEW

**Comment by tgorochowik** [comment]
This looks very promising!

I have a few questions:
* why do we need to use the update preview button? Can we update it each time any of the setting changes?
* reloading the preview seems kind of slow - what is the reason for this? is it the recalculation of the pixels? or is it the gui itself? Can something be done about this (this doesn't have to be a part of this PR, but please create an issue for this if this is a separate problem, this needs to be addressed)

**Comment by tgorochowik** [comment]
Also make sure to fix the issues reported by CI before merging this

**Comment by Ty7ak** [comment]
> 
> 
> This looks very promising!
> 
> I have a few questions:
> 
>     * why do we need to use the update preview button? Can we update it each time any of the setting changes?
> 
>     * reloading the preview seems kind of slow - what is the reason for this? is it the recalculation of the pixels? or is it the gui itself? Can something be done about this (this doesn't have to be a part of this PR, but please create an issue for this if this is a separate problem, this needs to be addressed)

Updating the image preview upon modifying any value will be implemented, that's a good sugestion.

**Comment by blazejulanowicz** [comment]
>     * reloading the preview seems kind of slow - what is the reason for this? is it the recalculation of the pixels? or is it the gui itself? Can something be done about this (this doesn't have to be a part of this PR, but please create an issue for this if this is a separate problem, this needs to be addressed)

When it comes to reloading time it was previous backend way of interpreting data. It has been changed in #24  - data with full bytes integers is interpreted as an array of numbers, but when it comes to data with shorter integers (i. e. 5-6-5 bits in RGB565) we need to do some bit shifting - that's why they are slower to parse.

**Review by blazejulanowicz — APPROVED** [review]

**Pull request merged**
