### PR TITLE
Add YUV support (packed and semiplanar), refactor RGB support, refactor and add tests

### LINKED ISSUE #18: Add packed YUV support
Utility should be expanded by packed YUV color format support.

Color formats that should be implemented:
- [UYVY](https://www.loc.gov/preservation/digital/formats/fdd/fdd000365.shtml)
- [YUY2](https://www.kernel.org/doc/html/v4.12/media/uapi/v4l/pixfmt-yuyv.html)
- and all other components order variations
- Should be considered - [normally packed YUVs](https://www.kernel.org/doc/html/v4.12/media/uapi/v4l/pixfmt-packed-yuv.html)

Actually it depends on #17.

### LINKED ISSUE #19: Refactor tests - mocks
Current unit tests does not use mocks, so they aren't actually "unit".
They should be refactored, so there is no dependencies on other classes.

That issue also includes refactoring CI - it should support tests with mocks!

Mocking library that should be used - [pytest-mock](https://github.com/pytest-dev/pytest-mock)

### PR DESCRIPTION
**Pull request by blazejulanowicz**
I've refactored RGB support, now its only one parser for entire RGBA (including RGBA, BGRA etc.). Future color formats implementations should follow same structure i. e. ARGB or XRGB.

There is now YUV support included. For now there are packed 4:2:2 formats (YUY2/YUYV, UYVY) and semi-planar 4:2:0 formats (NV12 and NV21). For now only 8-bit formats are allowed.

I've also refactored parser tests - now they are using mocks.

Closes #18, fixes #19.

### CODE REVIEW

**Review by DopartDawid — APPROVED** [review]
LGTM in general, good idea with the universal RGBA parser

**Comment by tgorochowik** [comment]
> EDIT: Now you CAN'T open files providing any resolution - if there will be not enough data in file to build an image in chosen color format and resolution, exception will be thrown.

Is there a reason for this? We'd like to be able to use this app with malformed frames too. And probably with dumps containing multiple frames too.

So ideally we'd like to be able to just provide the width and it should be enough to calculate the height for the data it receives - the data can be padded with zeroes if it ends in the middle of the last line.

**Comment by blazejulanowicz** [comment]
> > EDIT: Now you CAN'T open files providing any resolution - if there will be not enough data in file to build an image in chosen color format and resolution, exception will be thrown.
> 
> Is there a reason for this? We'd like to be able to use this app with malformed frames too. And probably with dumps containing multiple frames too.
> 
> So ideally we'd like to be able to just provide the width and it should be enough to calculate the height for the data it receives - the data can be padded with zeroes if it ends in the middle of the last line.

This was available in previous versions, but I thought that garbage data is not useful here so I removed it. But if you need that functionality, I will restore that right away.

**Comment by blazejulanowicz** [comment]
I've changed the way data is interpreted - now only width should be provided and height is calculated by parsing function.
For now I leave `height` argument in `parse` method so it is compliant with current version of CLI and GUI. This will be changed in the future.

**Pull request merged**
